version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "sleep 10 && python app.py"
    tty: true 
    volumes:
      - .:/app
      - transaction_files:/app/static/transaction_files
      - database_backups:/app/database_backups
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/office_services
      SECRET_KEY: your_secret_key_here
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: office_services
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  # خدمة Jenkins الجديدة
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/var/jenkins_home/workspace/office-services
    networks:
      - default

volumes:
  postgres_data:
  transaction_files:
  database_backups:
  jenkins_data: